'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {

      return queryInterface.bulkInsert('Games', [

        { name: 'Call of Duty: Black Ops Cold War', genre: 'FPS', description: 'Call of Duty: Black Ops Cold War is a 2020 first-person shooter video game developed by Treyarch and Raven Software and published by Activision.', releaseDate: '11-13-2020', platform: 'PS5,Xbox, PC' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Spider-Man: Miles Morales', genre: 'Action-Adventure', description: "The game is the second installment in the Marvel's Spider-Man series, following Marvel's Spider-Man (2018), and depicts Miles' struggle to balance the duties of his civilian persona and Spider-Man when his new home, Harlem, is threatened by a war between the Roxxon Energy Corporation and the Tinkerer's high-tech criminal army, the Underground.", releaseDate: '11-12-2020', platform: 'PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Assassin’s Creed Valhalla', genre: 'Action Role-Playing', description: "It is the twelfth major installment and the twenty-second release in the Assassin's Creed series, and a successor to the 2018's Assassin's Creed Odyssey. Set in the years 872–878 AD, the game recounts a fictional story during the Viking invasion of Britain. The player controls Eivor, a Viking raider who becomes embroiled in the conflict between the Brotherhood of Assassins and the Templar Order", releaseDate: '11-10-2020', platform: 'PS5,XBox, PC' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Demon’s Souls', genre: 'Action role-playing', description: "Demon's Souls is set in Boletaria, a kingdom consumed by a dark being called the Old One, following its release through the use of forbidden Soul Arts. Players take on the role of a hero brought to Boletaria to kill its fallen king Allant and pacify the Old One. Gameplay has players navigating five different worlds from a hub called the Nexus, with a heavy emphasis on challenging combat and mechanics surrounding player death and respawning. Online multiplayer allows both player cooperation and world invasions featuring player versus player combat.", releaseDate: '11-12-2020', platform: 'PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Cyberpunk 2077', genre: 'Action role-playing', description: 'Cyberpunk 2077 is played in a first-person perspective as V, a mercenary whose voice, face, hairstyles, body type and modifications, background, and clothing are customisable. The open world metropolis Night City, California, consists of six regions—the corporate City Centre, immigrant-inhabited Watson, luxurious Westbrook, suburban Heywood, gang-infested Pacifica, and industrial Santo Domingo. Its surrounding area, the Badlands, can also be explored.', releaseDate: '11-17-2020', platform: 'PS5, Xbox, PC' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Dirt 5', genre: 'Racing Game', description: 'Dirt 5 is a racing game focused on off-road racing. Disciplines within the game include rallycross, ice racing, Stadium Super Trucks and off-road buggies. Players can compete in events in a wide range of locations, namely Arizona, Brazil, China, Greece, Italy, Morocco, Nepal, New York City, Norway and South Africa.[1] The game includes a dynamic weather system and seasons, which affect the racing; for example, the player can only compete in ice racing events in New York during winter months. A four-player splitscreen system is also introduced into the game', releaseDate: '11-06-2020', platform: 'PS5, Xbox, PC' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Ghost of Tsushima', genre: 'Action-adventure', description: 'Ghost of Tsushima is an action-adventure stealth game played from a third-person perspective. The game features a large open world, without waypoints, which can be explored without guidance. Players can travel to different parts of the world on horseback.', releaseDate: '11-17-2020', platform: 'PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Marvel’s Avengers', genre: 'Action-adventure/Role-Playing', description: "Marvel's Avengers is a third-person, action-adventure game that combines an original, cinematic story with single-player and co-operative gameplay. The game can be played offline as a single-player experience or online with up to four people during certain aspects of the game.", releaseDate: '09-04-2020', platform: 'PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Yakuza: Like A Dragon', genre: 'Role-Playing', description: "RISE LIKE A DRAGON. Become Ichiban Kasuga, a low-ranking yakuza grunt left on the brink of death by the man he trusted most. Take up your legendary bat and get ready to crack some underworld skulls in dynamic RPG combat set against the backdrop of modern-day Japan.", releaseDate: '11-10-2020', platform: 'PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'NBA 2K21', genre: 'Sports', description: 'NBA 2K21 is the latest title in the world-renowned, best-selling NBA 2K series, delivering an industry-leading sports video game experience.', releaseDate: '11-12-2020', platform: 'PS5, Xbox' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'The Legend of Zelda: Breath of the Wild', genre: 'Adventure', description: "Breath of the Wild is part of the Legend of Zelda franchise and is set at the end of the Zelda timeline; the player controls Link, who awakens from a hundred-year slumber to defeat Calamity Ganon and save the kingdom of Hyrule.", releaseDate: '3-3-2017', platform: 'Nintendo Switch, Wii U' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Super Mario Odyssey', genre: 'Adventure', description: "An entry in the Super Mario series, it follows Mario and Cappy, a sentient hat that allows Mario to control other characters and objects, as they journey across various kingdoms to save Princess Peach from his nemesis Bowser, who plans to forcibly marry her.", releaseDate: '10-7-2017', platform: 'Nintendo Switch' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Pokemon Sword', genre: 'Role-playing', description: "Pokemon Sword is a 2019 role-playing video game developed by Game Freak and published by The Pokémon Company and Nintendo for the Nintendo Switch. They are the first installments in the eighth generation of the Pokémon video game series and the second in the series, following Pokémon: Let's Go, Pikachu! and Let's Go, Eevee!", releaseDate: '11-15-2019', platform: 'Nintendo Switch' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Mario Kart 8', genre: 'Kart Racing', description: "Mario Kart 8 is a kart racing video game developed and published by Nintendo. It was released for the Wii U in May 2014. It retains Mario Kart series game mechanics, where players control Mario franchise characters in kart racing, collecting a variety of items to hinder opponents or gain advantages in the race. Mario Kart 8 introduces anti-gravity driving on walls or ceilings, and allows players to bump into each other for a short boost.", releaseDate: '04-28-2017', platform: 'Nintendo Switch, Wii U' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Luigi’s Mansion 3', genre: 'Action-adventure', description: "The game sees players taking on the role of Luigi who must explore a haunted hotel, incorporating different themes on each floor, and rescue his friends from the ghosts that inhabit it, after the group is tricked into visiting it for a vacation by King Boo.", releaseDate: '10-31-2019', platform: 'Nintendo Switch' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Diablo III', genre: 'Action role-playing', description: "Players choose to play as one of seven character classes – Barbarian, Crusader, Demon Hunter, Monk, Necromancer, Witch Doctor, or Wizard – and are tasked with defeating the Lord of Terror, Diablo, as in previous games in the series.", releaseDate: '05-15-2012', platform: 'Nintendo Switch, Playstation 4, Xbox One, PC' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'The Elder Scrolls V: Skyrim', genre: 'Action role-playing', description: "The game's main story revolves around the player's character, the Dragonborn, on their quest to defeat Alduin the World-Eater, a dragon who is prophesied to destroy the world.", releaseDate: '11-11-2011', platform: 'PS3, PS4, Xbox One, Nintendo Switch' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Mario Tennis Aces', genre: 'Sports', description: "The gameplay of Mario Tennis Aces consists of playing matches of tennis with various characters from the Super Mario series.", releaseDate: '06-22-2018', platform: 'Nintendo Switch' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Rocket League', genre: 'Sports', description: "Described as soccer, but with rocket-powered cars, Rocket League has up to eight players assigned to each of the two teams, using rocket-powered vehicles to hit a ball into their opponent's goal and score points over the course of a match.", releaseDate: '07-07-2015', platform: 'PS4, Xbox One, PC, Nintendo Switch, PS5, Nintendo Switch' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Dead Cells', genre: 'Roguelike', description: "In the game, the player takes the role of an amorphous, gelatinous creature that takes control of a corpse in a dungeon, through which they must fight their way out.", releaseDate: '08-07-2018', platform: 'PC, Nintendo Switch, PS4, Xbox One' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Grand Theft Auto V', genre: 'Action-Adventure', description: "Set within the fictional state of San Andreas, based on Southern California, the single-player story follows three protagonists—retired bank robber Michael De Santa, street gangster Franklin Clinton, and drug dealer and arms smuggler Trevor Philips—and their efforts to commit heists while under pressure from a corrupt government agency and powerful criminals. The open world design lets players freely roam San Andreas' open countryside and the fictional city of Los Santos, based on Los Angeles.", releaseDate: '11-17-2013', platform: 'PS5, Xbox, PC' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'FIFA 21', genre: 'Sports', description: "FIFA 21 is a football simulation video game published by Electronic Arts as part of the FIFA series.", releaseDate:  '12-03-2020', platform: 'Xbox, PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Lego Star Wars: The Skywalker Saga', genre: 'Action-adventure ', description: "The galaxy is yours with LEGO Star Wars: The Skywalker Saga; Play all nine saga films and experience fun filled adventure in a galaxy far, far away", releaseDate: '02-28-2021', platform: 'Xbox, PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Hitman 3', genre: 'Stealth', description: "Hitman 3 is a stealth game played from a third-person perspective and players once again assume control of assassin Agent 47. In the game, 47 travels to various locations and carries out contracted assassinations, continuing the story of the last two games.", releaseDate: '01-20-2021', platform: 'Xbox, PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Forza Horizon 4', genre: 'Racing', description: "Forza Horizon 4 is a racing video game set in an open world environment based in a fictionalised Great Britain, with regions that include condensed representations of Edinburgh, the Lake District (including Derwentwater), Ambleside and the Cotswolds (including Broadway), among others.", releaseDate: '11-10-2020', platform: 'Xbox' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Resident Evil Village', genre: 'Survival Horror', description: "Resident Evil Village is set a few years after Resident Evil 7. Ethan Winters returns as the protagonist. Ethan has been living with his wife Mia when Chris Redfield suddenly appears and kidnaps him to a mysterious European village. The game also features an antagonist known as Alcina Dimitrescu.", releaseDate: '05-07-2021', platform: 'Xbox, PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Halo Infinite', genre: 'FPS', description: "According to Microsoft, Master Chief returns in Halo Infinite, the third chapter of the Reclaimer Saga, with his greatest adventure yet to save humanity. The storyline of Halo Infinite will be 'much more human', with the Master Chief playing a more central role than in Halo 5: Guardians.", releaseDate: '08-01-2021', platform: 'Xbox' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Watch Dogs Legion', genre: 'Action-adventure', description: "Watch Dogs: Legion is an action-adventure game played from a third-person perspective, and taking place within an open world setting based upon London, which can be explored either on foot ─ utilizing parkour moves ─ vehicles, or fast-travelling via the city's Underground stations.", releaseDate: '11-12-2020', platform: 'Xbox, PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Madden NFL 21', genre: 'Sports', description: "Madden NFL 21 is an American football video game based on the National Football League, developed by EA Tiburon and published by Electronic Arts. It is an installment of the long-running Madden NFL series.", releaseDate: '08-28-2020', platform: 'Xbox, PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Gears 5', genre: 'Third-Person Shooter', description: "Gears 5 takes place months after the events of Gears of War 4 and focuses on Kait Diaz (Laura Bailey), an Outsider who is descended from Myrrah (Carolyn Seymour), Queen of the Locust Horde. As Kait, the player must uncover the origins of the Locust and the truth behind her family history. James Dominic JD Fenix (Liam McIntyre), his best friend Delmont Del Walker (Eugene Byrd), and JD's father Marcus Fenix (John DiMaggio) also return.", releaseDate: '11-10-2020', platform: 'Xbox, PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'The Witcher 3: Wild Hunt', genre: 'Action role-playing', description: "The game takes place in a fictional fantasy world based on Slavonic mythology. Players control Geralt of Rivia, a monster slayer for hire known as a Witcher, and search for his adopted daughter, who is on the run from the otherworldly Wild Hunt.", releaseDate: '05-19-2015', platform: 'PC, PS4, Xbox One, Nintendo Switch, PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Ghostrunner', genre: 'Action', description: "As Jack the Ghostrunner, the player must traverse dangerous environments by dashing, jumping, wall-running, and grappling. The player will also encounter enemies, which must be handled carefully, as both enemies and the player can be killed in one hit.", releaseDate: '10-27-2020', platform: 'PC, PS4, Xbox One, Nintendo Switch, PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Control', genre: 'Action-adventure', description: "The game revolves around the Federal Bureau of Control (FBC), a secret U.S. government agency tasked with containing and studying phenomena that violate the laws of reality. ", releaseDate: '08-27-2019', platform: 'PC, PS4, Xbox One, Nintendo Switch, PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'World of Warcraft: Shadowlands', genre: 'Role-playing', description: "In what Blizzard has called a New Game+ experience, newly created characters have an updated starting experience on an island called Exile's Reach, which introduces them to the game and its systems.", releaseDate: '11-23-2020', platform: 'PC' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Microsoft Flight Simulator', genre: 'Amateur flight simulation', description: "It is one of the longest-running, best-known, and most comprehensive home flight simulator programs on the market. It was an early product in the Microsoft application portfolio and differed significantly from Microsoft's other software, which was largely business-oriented. At 38 years old, it is the longest-running software product line for Microsoft, predating Windows by three years.", releaseDate: '08-18-2020', platform: 'PC' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Monster Hunter: World', genre: 'Action role-playing', description: "In the game, the player takes the role of a Hunter, tasked to hunt down and either kill or trap monsters that roam in one of several environmental spaces.", releaseDate: '01-26-2018', platform: 'PS4, Xbox One, PC' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Death Stranding', genre: 'Action', description: "The game is set in the United States following a cataclysmic event which caused destructive creatures to begin roaming the Earth. Players control Sam Porter Bridges (Norman Reedus), a courier tasked with delivering supplies to isolated colonies and reconnecting them via a wireless communications network.", releaseDate: '11-08-2019', platform: 'PS4, PC' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Red Dead Redemption 2', genre: 'Action-adventure', description: "The game is presented through both first and third-person perspectives, and the player may freely roam in its interactive open world. Gameplay elements include shootouts, heists, hunting, horseback riding, interacting with non-player characters, and maintaining the character's honor rating through moral choices and deeds.", releaseDate: '10-26-2018', platform: 'PS4, PC' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Doom Eternal', genre: 'First-person shooter', description: "Players once again take on the role of the Doom Slayer who battles the demonic forces of Hell, from a first-person perspective. The game continues its predecessor's emphasis on push-forward combat, encouraging the player to aggressively engage enemies in order to acquire health, ammo, and armor.", releaseDate: '03-20-2020', platform: 'PS4, PC, Xbox One, Nintendo Switch, PS5' , createdAt: new Date(), updatedAt: new Date()},
        { name: 'Half-Life: Alyx', genre: 'First-person shooter', description: "Players control Freeman's ally Alyx Vance as she and her father Eli Vance fight the Combine, an alien empire that has conquered Earth.", releaseDate: '03-23-2020', platform: 'PC' , createdAt: new Date(), updatedAt: new Date()},



      ], {});
  },

  down: (queryInterface, Sequelize) => {

      return queryInterface.bulkDelete('Games', null, {});

  }
};
